# Generated by Django 5.2.8 on 2025-12-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='ingredient_pics'),
        ),
    ]
